function fig = cocka()
% This is the machine-generated representation of a Handle Graphics object
% and its children.  Note that handle values may change when these objects
% are re-created. This may cause problems with any callbacks written to
% depend on the value of the handle at the time the object was saved.
% This problem is solved by saving the output as a FIG-file.
%
% To reopen this object, just type the name of the M-file at the MATLAB
% prompt. The M-file and its associated MAT-file must be on your path.
% 
% NOTE: certain newer features in MATLAB may not have been saved in this
% M-file due to limitations of this format, which has been superseded by
% FIG-files.  Figures which have been annotated using the plot editor tools
% are incompatible with the M-file/MAT-file format, and should be saved as
% FIG-files.

load cocka
global jazyk scrsz
[X,m]=imread('cocka.jpg');
texty=[{'Èoèka','Ohnisková vzdálenost èoèky [m]:','Délka prostoru za soustavou [m]:','Pokraèuj'};
{'Lens','Focus length of the lens [m]:','Length of the space behind the system [m]:','Continue'}];

h0 = figure('Color',[0.8 0.8 0.8], ...
	'Colormap',mat0, ...
	'FileName','cocka.m', ...
	'MenuBar','none', ...
	'Name',texty{jazyk,1}, ...
	'NumberTitle','off', ...
	'PaperPosition',[18 180 576 432], ...
	'PaperUnits','points', ...
	'Position',[scrsz(3)/2-155 scrsz(4)/2-95 310 190], ...
	'Tag','cocka', ...
	'ToolBar','none');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[15 115 130 12], ...
	'String',texty{jazyk,2}, ...
	'Style','text', ...
	'Tag','ohniskotext');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[180 115 35 15], ...
	'String','5', ...
	'Style','edit', ...
	'Tag','ohnisko');

h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[15 90 160 12], ...
	'String',texty{jazyk,3}, ...
	'Style','text', ...
	'Tag','delkatextza');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[180 90 35 15], ...
	'String','5', ...
	'Style','edit', ...
	'Tag','delkaza');

h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Callback','cocka_vypocet', ...
	'ListboxTop',0, ...
	'Position',[140 40 60 20], ...
	'String',texty{jazyk,4}, ...
	'Tag','Pushbutton1');
h1 = axes('Parent',h0, ...
	'Box','on', ...
	'CameraUpVector',[0 -1 0], ...
	'Color',[1 1 1], ...
	'ColorOrder',mat1, ...
	'Layer','top', ...
	'Tag','Axes1', ...
	'Visible','off', ...
	'XColor',[0 0 0], ...
	'XLim',[0.5 230.5], ...
	'XLimMode','manual', ...
	'YColor',[0 0 0], ...
	'YDir','reverse', ...
	'YLim',[0.5 100.5], ...
	'YLimMode','manual', ...
	'ZColor',[0 0 0]);
h2 = image('Parent',h1, ...
	'CData',mat2, ...
	'Tag','Axes1Image1', ...
	'XData',[1 230], ...
	'YData',[1 100]);
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','center', ...
	'Position',mat3, ...
	'Tag','Axes1Text4', ...
	'VerticalAlignment','cap', ...
	'Visible','off');
set(get(h2,'Parent'),'XLabel',h2);
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','center', ...
	'Position',[-30.29497907949791 51.26923076923076 9.160254037844386], ...
	'Rotation',90, ...
	'Tag','Axes1Text3', ...
	'VerticalAlignment','baseline', ...
	'Visible','off');
set(get(h2,'Parent'),'YLabel',h2);
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','right', ...
	'Position',[-38.95606694560669 -8.21794871794873 9.160254037844386], ...
	'Tag','Axes1Text2', ...
	'Visible','off');
set(get(h2,'Parent'),'ZLabel',h2);
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','center', ...
	'Position',mat4, ...
	'Tag','Axes1Text1', ...
	'VerticalAlignment','bottom', ...
	'Visible','off');
set(get(h2,'Parent'),'Title',h2);
image(X);
set(gca,'Visible','off','Position',[0.1 0.1 0.33 0.45]); 
if nargout > 0, fig = h0; end
