function cocka_vypocet;
global jazyk R1 W1 q1 scrsz a1 b1 k;

%sejme z predesleho okna hodonoty
handle=findobj('Tag','ohnisko');
f=str2num(get(handle,'String'));

handle=findobj('Tag','delkaza');
z0=str2num(get(handle,'String'));

close;

A=1;B=0;C=-1/f;D=1;
q2=(A*q1+B)/(C*q1+D);
W2=sqrt((2*(A*a1+B)^2+(A*b1)^2)/(k*b1*((A*a1+B)*C-A*(C*a1+D))));%vypocet R2 za prvkem
R2=((A*a1+B)^2+(A*b1)^2)/((A*a1+B)*(C*a1+D)-A*(C*a1+D));			%vypocet W2 za prvkem

load cocka_vypocet
texty=[{'Èoèka','Parametry svazku pred optickım prvkem','Polomìr svazku W1 je','Polomìr vlnoplochy R1 je','Parametry svazku za optickım prvkem','Znovu','Konec'};
{'Lens','Parameters in front of optical element','Radius of beam W1 is','Radius of waveplane R1 is','Parameters behind optical element','Again','End'}];

h0 = figure('Color',[0.8 0.8 0.8], ...
	'Colormap',mat0, ...
	'MenuBar','none', ...
	'Name',['Gauss 1.0: ' texty{jazyk,1}], ...
	'NumberTitle','off', ...
	'PaperPosition',[18 180 576 432], ...
	'PaperUnits','points', ...
	'Position',[scrsz(3)/2-350 scrsz(4)/2-207 700 414], ...
	'Renderer','zbuffer', ...
	'RendererMode','manual', ...
	'Resize','off', ...
	'Tag','zobraz', ...
	'ToolBar','none');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'ListboxTop',0, ...
	'Position',[341.25 50 45 120], ...
	'String','', ...
	'Style','text', ...
	'Tag','Z-graf');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'ListboxTop',0, ...
	'Position',[389.25 50 45 120], ...
	'String','', ...
	'Style','text', ...
	'Tag','W2-graf');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'ListboxTop',0, ...
	'Position',[435.75 50 45 120], ...
	'String','', ...
	'Style','text', ...
	'Tag','R2-graf');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',[335.25 170 159 15], ...
	'String','Z [m]      W2 [mm]     R2 [m]', ...
	'Style','text', ...
	'Tag','StaticText2');

h1 = axes('Parent',h0, ...
	'CameraUpVector',[0 1 0], ...
	'CameraUpVectorMode','manual', ...
	'Color',[1 1 1], ...
	'ColorOrder',mat1, ...
	'NextPlot','add', ...
	'PlotBoxAspectRatioMode','manual', ...
	'Position',mat2, ...
	'Tag','Axes1', ...
	'WarpToFill','off', ...
	'WarpToFillMode','manual', ...
	'XColor',[0 0 0], ...
	'YColor',[0 0 0], ...
	'ZColor',[0 0 0]);
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','center', ...
	'Position',mat47, ...
	'String','Z [m]', ...
	'Tag','Axes1Text4', ...
	'VerticalAlignment','cap');
set(get(h2,'Parent'),'XLabel',h2);
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','center', ...
	'Position',[-1.6 0 17], ...
	'Rotation',90, ...
	'String','X [mm]', ...
	'Tag','Axes1Text3', ...
	'VerticalAlignment','baseline');
set(get(h2,'Parent'),'YLabel',h2);
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','right', ...
	'Position',[-2.3 1 17], ...
	'Tag','Axes1Text2', ...
	'Visible','off');
set(get(h2,'Parent'),'ZLabel',h2);
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','center', ...
	'Position',[2 1 17], ...
	'Tag','Axes1Text1', ...
	'VerticalAlignment','bottom');
set(get(h2,'Parent'),'Title',h2);

h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',[330 270 195 12], ...
	'String',texty{jazyk,2}, ...
    'HorizontalAlignment','left', ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'ListboxTop',0, ...
	'Position',[340 250 95 10], ...
	'String',texty{jazyk,3}, ...
    'HorizontalAlignment','left', ...
	'Style','text', ...
	'Tag','StaticText3');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'ListboxTop',0, ...
	'Position',[440 250 30 10], ...
	'String','', ...
	'Style','text', ...
	'Tag','W1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'ListboxTop',0, ...
	'Position',[465 250 30 10], ...
	'String',' mm,', ...
	'Style','text', ...
	'Tag','StaticText5');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'ListboxTop',0, ...
	'Position',[340 230 110 10], ...
	'String',texty{jazyk,4}, ...
    'HorizontalAlignment','left', ...
	'Style','text', ...
	'Tag','StaticText6');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'ListboxTop',0, ...
	'Position',[440 230 30 10], ...
	'String','', ...
	'Style','text', ...
	'Tag','R1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'ListboxTop',0, ...
	'Position',[465 230 30 10], ...
	'String',' m.', ...
	'Style','text', ...
	'Tag','StaticText8');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',[330 185 185 20], ...
	'String',texty{jazyk,5}, ...
    'HorizontalAlignment','left', ...
	'Style','text', ...
	'Tag','StaticText9');

h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Callback','zadani', ...
	'ListboxTop',0, ...
	'Position',[360 30 55 15], ...
	'String',texty{jazyk,6}, ...
	'Tag','Znovu');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Callback','close all', ...
	'ListboxTop',0, ...
	'Position',[430 30 45 15], ...
	'String',texty{jazyk,7}, ...
	'Tag','Pushbutton2');

zz=0;
figure(h0);
for z=0.1:0.5:z0+0.1
   zz=zz+1; %indexovani
   zn=z-0.1; 		%hodnota pro rozvoj v z-souradnici
   W2z(zz)=sqrt((W2)^2*(1+zn/R2)^2+(2*zn/(k*W2))^2);									%rozvoj W2z
   R2z(zz)=((R2+zn)^2*(k*W2^2)^2+4*zn^2*R2^2)/((R2+zn)*(k*W2^2)^2+4*zn*R2^2); %rozvoj R2z
   Z(zz)=zn;			%z-souradnice pro vypis
   delitel=W2z(zz)/10;
   x=0;
   yy=0;
   pom=0;
   for y=0:delitel:W2z(zz)
      pom=pom+1;
      yy(pom)=y;
      x(pom)=sqrt(R2z(zz)^2-(y)^2);
      x(pom)=x(pom)-abs(R2z(zz))+zn;
   end
   hold on;
 	plot(x,yy);
   set(gca,'PlotBoxAspectRatio',[1 1 1]);
   plot(x,-yy);
end

W2z=round(W2z*100)/100;
R2z=round(R2z*100)/100;

set(findobj('Tag','W1'),'String',num2str(W1));
set(findobj('Tag','R1'),'String',num2str(R1));
set(findobj('Tag','Z-graf'),'String',num2str(Z'));
set(findobj('Tag','W2-graf'),'String',num2str(W2z'));
set(findobj('Tag','R2-graf'),'String',num2str(R2z'));

if nargout > 0, fig = h0; end
