function fig = inform(zadany_jazyk)
% This is the machine-generated representation of a Handle Graphics object
% and its children.  Note that handle values may change when these objects
% are re-created. This may cause problems with any callbacks written to
% depend on the value of the handle at the time the object was saved.
% This problem is solved by saving the output as a FIG-file.
%
% To reopen this object, just type the name of the M-file at the MATLAB
% prompt. The M-file and its associated MAT-file must be on your path.
% 
% NOTE: certain newer features in MATLAB may not have been saved in this
% M-file due to limitations of this format, which has been superseded by
% FIG-files.  Figures which have been annotated using the plot editor tools
% are incompatible with the M-file/MAT-file format, and should be saved as
% FIG-files.
close;
load Inform
global jazyk scrsz
jazyk=zadany_jazyk;
texty=[{'Gaussùv svazek 1.0',
    'Základní informace',
    'Pokraèuj',
    '',
'Program poèítá parametry gaussovského svazku po prùchodu optickım ',
'prvkem a vısledky zobrazuje graficky na urèité vzdálenosti za optickım', 
'prvkem.',
'Zadává se vlnová délka, šíøka gaussova svazku a polomìr vlnoplochy. Dále si je ',
'mono vybrat z urèitého optického prvku. K dispozici jsou tyto prvky:',
'		- volnı prostor',
'		- tenká èoèka',
'		- rovinné zrcadlo',
'		- kulové zrcadlo',
'		- rovinné rozhraní',
'		- kulové rozhraní',
'Po zvolení jednoho typu optického rozhraní jste vyzváni k zadání', 
'parametrù soustavy a dále se zobrazí ji graficky vısledek a takté tabelární',
'vıpis parametrù svazku pøi rozvoji v z-souøadnici',
''} {'Gaussian beam 1.0',
'Basic information',
'Continue',
'',
'Program computes parameters of gaussian beam after way trough optical element',
'and displays graphically the results in certain distance behind the element.',
'Wavelenght, width of beam and diameter of the waveplane need to be defined. ',
'One can choose from following optical systems:',
'		- empty space',
'		- thin lens',
'		- plane mirror',
'		- ball mirror',
'		- plane boundary',
'		- ball boundery',
'After choosing of optical interface, parameters of such are defined. Results',
'are displayed both in graphical and table form. The table is list of parameters',
'of the beam with respect to z-coordinate.',
'',
''}];

   h0 = figure('Color',[0.8 0.8 0.8], ...
	'Colormap',mat0, ...
	'FileName','Inform.m', ...
	'MenuBar','none', ...
	'Name',texty{1,jazyk}, ...
	'NumberTitle','off', ...
	'PaperPosition',[20 200 550 400], ...
	'PaperUnits','points', ...
	'Position',[scrsz(3)/2-225 scrsz(4)/2-156 450 312], ...
	'Resize','off', ...
	'Tag','Info', ...
	'ToolBar','none');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',20, ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',[60.75 193 204.75 27.75], ...
	'String',texty{2,jazyk}, ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[10.5 25.5 307.5 165], ...
  	'String',texty(4:end,jazyk), ...
	'Style','text', ...
	'Tag','StaticText2');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'Callback','zadani', ...
	'ListboxTop',0, ...
	'Position',[142.5 7.5 45 15], ...
	'String',texty{3,jazyk}, ...
	'Tag','Pushbutton1', ...
	'UserData','[ ]');
if nargout > 0, fig = h0; end
