function prostor;
close all;
load prostor
%Zadani hodnot pro vypocet
global jazyk R1 W1 q1 scrsz a1 b1 k;
[X,m]=imread('prostor.jpg');
texty=[{'Volnı prostor','Délka volného prostoru [m]:','Délka prostoru za soustavou [m]:','Pokraèuj'};
{'Empty space','Length of empty space [m]:','Length of the space behind the system [m]:','Continue'}];

h0 = figure('Color',[0.8 0.8 0.8], ...
	'Colormap',mat0, ...
	'FileName','zadani.m', ...
	'Name',texty{jazyk,1}, ...
	'NumberTitle','off', ...
 	'MenuBar','none', ...
	'PaperPosition',[18 180 576 432], ...
	'PaperUnits','points', ...
	'Position',[scrsz(3)/2-155 scrsz(4)/2-95 310 190], ...
	'Tag','volny prostor', ...
   'ToolBar','none',...
	'Resize','off');
h1 = axes('Parent',h0, ...
	'CameraUpVector',[0 1 0], ...
	'Color',[1 1 1], ...
	'Tag','Axes1', ...
	'Visible','off', ...
	'XColor',[0 0 0], ...
	'YColor',[0 0 0], ...
	'ZColor',[0 0 0]);
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[15 115 110 12], ...
	'String',texty{jazyk,2}, ...
	'Style','text', ...
	'Tag','delkatext');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[180 115 35 15], ...
   'String','5', ...
	'Style','edit', ...
   'Tag','delka');

h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[15 90 160 12], ...
	'String',texty{jazyk,3}, ...
	'Style','text', ...
	'Tag','delkatextza');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[180 90 35 15], ...
   'String','5', ...
	'Style','edit', ...
   'Tag','delkaza');


h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
   'BackgroundColor',[0.8 0.8 0.8], ...
   'Callback','prostor_vypocet', ...
	'ListboxTop',0, ...
	'Position',[140 40 60 20], ...
	'String',texty{jazyk,4}, ...
   'Tag','Pushbutton1');
image(X);
set(gca,'Visible','off','Position',[0.1 0.1 0.33 0.45]); 
if nargout > 0, fig = h0; end

