function fig = zadani()
% This is the machine-generated representation of a Handle Graphics object
% and its children.  Note that handle values may change when these objects
% are re-created. This may cause problems with any callbacks written to
% depend on the value of the handle at the time the object was saved.
% This problem is solved by saving the output as a FIG-file.
%
% To reopen this object, just type the name of the M-file at the MATLAB
% prompt. The M-file and its associated MAT-file must be on your path.
% 
% NOTE: certain newer features in MATLAB may not have been saved in this
% M-file due to limitations of this format, which has been superseded by
% FIG-files.  Figures which have been annotated using the plot editor tools
% are incompatible with the M-file/MAT-file format, and should be saved as
% FIG-files.

global jazyk scrsz
load zadani
close
texty=[{'Parametry Gaussova svazku','Vlnová délka [nm]:','Šíøka svazku [mm]:','Polomìr vlnoplochy [m]:','Parametry'};
{'Parameters of Gaussian beam','Wavelength [nm]:','Width of the beam [mm]:','Radius of waveplane [m]:','Parameters'}];

h0 = figure('Color',[0.8 0.8 0.8], ...
	'Colormap',mat0, ...
	'FileName','zadani.m', ...
	'MenuBar','none', ...
	'Name',texty{jazyk,1}, ...
	'NumberTitle','off', ...
	'PaperPosition',[18 180 576 432], ...
	'PaperUnits','points', ...
	'Position',[scrsz(3)/2-130 scrsz(4)/2-90 260 180], ...
	'Tag','zadani', ...
	'ToolBar','none');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[15 105 80 12], ...
	'String',texty{jazyk,2}, ...
	'Style','text', ...
	'Tag','lambda');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[15 75 100 12], ...
	'String',texty{jazyk,3}, ...
	'Style','text', ...
	'Tag','šíøka');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[15 45 120 12], ...
	'String',texty{jazyk,4}, ...
	'Style','text', ...
	'Tag','polomìr');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[140 105 35 15], ...
	'String','750', ...
	'Style','edit', ...
	'Tag','vlndelka');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[140 75 35 15], ...
	'String','1', ...
	'Style','edit', ...
	'Tag','sirka');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[140 45 35 15], ...
	'String','10', ...
	'Style','edit', ...
	'Tag','polomer');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Callback','soustava', ...
	'ListboxTop',0, ...
	'Position',[118 15 57 15], ...
	'String',texty{jazyk,5}, ...
	'Tag','Pushbutton1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'ListboxTop',0, ...
	'Position',[15 5 90 25], ...
	'String',mat1{jazyk}, ...
	'Style','popupmenu', ...
	'Tag','Vyber', ...
	'Value',1);
if nargout > 0, fig = h0; end
